const FACES=['⚀','⚁','⚂','⚃','⚄','⚅'];
const COLORS=['#d80017','#2b7fff','#1da66b','#8e49e8'];
const DEMO_NAMES=['João Luís','Tomás','Ana','Carlos'];
const MAX_POS=29;
const CELL_TYPES=['start','normal','quiz','bonus','normal','challenge','normal','event','quiz','penalty','normal','bonus','challenge','normal','quiz','event','normal','penalty','bonus','quiz','normal','challenge','event','normal','quiz','bonus','penalty','normal','challenge','finish'];
const QUIZZES=[
{title:'História de Angola',question:'Em que ano foi proclamada a Independência de Angola?',options:['1972','1975','1979','2002'],answer:1,success:'+60 pontos por resposta correta.',fail:'Sem pontos nesta pergunta.'},
{title:'Conhecer a organização',question:'O que significa a sigla MPLA?',options:['Movimento Popular de Libertação de Angola','Movimento Patriótico Livre de Angola','Movimento Popular Laboral Angolano','Movimento para a Paz e Liberdade de Angola'],answer:0,success:'+60 pontos por resposta correta.',fail:'Sem pontos nesta pergunta.'},
{title:'Participação responsável',question:'Qual destas atitudes melhor representa uma participação cívica responsável?',options:['Espalhar rumores','Respeitar regras e dialogar','Impedir opiniões diferentes','Ignorar responsabilidades'],answer:1,success:'+50 pontos e reconhecimento.',fail:'A participação responsável exige respeito e diálogo.'},
{title:'Memória nacional',question:'Qual é a data da Independência Nacional de Angola?',options:['4 de Fevereiro','11 de Novembro','17 de Setembro','1 de Maio'],answer:1,success:'+60 pontos.',fail:'A resposta correta é 11 de Novembro.'},
{title:'Cultura de equipa',question:'Numa atividade coletiva, o que mais favorece o resultado da equipa?',options:['Coordenação','Isolamento','Atraso','Desinformação'],answer:0,success:'+50 pontos.',fail:'Coordenação é a melhor resposta.'},
{title:'Conhecimento rápido',question:'A capital de Angola é:',options:['Benguela','Huambo','Luanda','Lubango'],answer:2,success:'+40 pontos.',fail:'A resposta correta é Luanda.'}
];
const CHALLENGES=[
{title:'Missão Relâmpago',text:'Em 15 segundos, diga uma razão pela qual o conhecimento da história fortalece uma organização.',success:70,skip:-10},
{title:'Desafio de Equipa',text:'Escolha outro jogador e formule uma palavra que represente trabalho em equipa. O grupo decide se aceita.',success:60,skip:-10},
{title:'Memória Rápida',text:'Diga três províncias de Angola sem repetir nenhuma já mencionada nesta ronda.',success:65,skip:-10},
{title:'Compromisso',text:'Diga uma atitude concreta que demonstra disciplina numa equipa.',success:55,skip:-10},
{title:'Comunicação',text:'Em uma frase curta, explique por que uma mensagem clara ajuda uma equipa a cumprir objetivos.',success:60,skip:-10}
];
const BONUSES=[
{title:'Mobilização bem-sucedida',text:'Boa capacidade de organização. Avance mais 2 casas e ganhe 40 pontos.',move:2,points:40},
{title:'Espírito de equipa',text:'A equipa reconheceu o teu contributo. Ganhe 70 pontos.',move:0,points:70},
{title:'Conhecimento premiado',text:'Recebeu um bónus de aprendizagem. Avance 1 casa e ganhe 50 pontos.',move:1,points:50}
];
const PENALTIES=[
{title:'Falta de preparação',text:'A preparação ficou incompleta. Recue 2 casas e perca 20 pontos.',move:-2,points:-20},
{title:'Atraso na atividade',text:'O atraso teve consequência. Fique uma ronda sem jogar.',move:0,points:-10,skip:1},
{title:'Falha de coordenação',text:'A equipa perdeu ritmo. Recue 1 casa e perca 25 pontos.',move:-1,points:-25}
];
const EVENTS=[
{title:'Encontro de equipa',text:'Todos os jogadores recebem 20 pontos pela participação coletiva.',allPoints:20},
{title:'Ronda de conhecimento',text:'O jogador atual ganha 35 pontos e mantém a posição.',points:35},
{title:'Ação comunitária',text:'Avance 2 casas e ganhe 30 pontos.',move:2,points:30}
];
const state={players:[],current:0,round:1,awaiting:false,rolling:false,sound:true,finishedOrder:[],playerCount:2};
const els={};
document.addEventListener('DOMContentLoaded',()=>{
Object.assign(els,{setupScreen:document.getElementById('setupScreen'),gameScreen:document.getElementById('gameScreen'),playerCount:document.getElementById('playerCount'),playerInputs:document.getElementById('playerInputs'),startBtn:document.getElementById('startBtn'),quickDemoBtn:document.getElementById('quickDemoBtn'),gameBoard:document.getElementById('gameBoard'),dice:document.getElementById('dice'),rollBtn:document.getElementById('rollBtn'),turnName:document.getElementById('turnName'),turnToken:document.getElementById('turnToken'),roundLabel:document.getElementById('roundLabel'),turnHint:document.getElementById('turnHint'),centerMessage:document.getElementById('centerMessage'),scoreList:document.getElementById('scoreList'),gameLog:document.getElementById('gameLog'),playersAlive:document.getElementById('playersAlive'),newGameBtn:document.getElementById('newGameBtn'),soundBtn:document.getElementById('soundBtn'),fullscreenBtn:document.getElementById('fullscreenBtn'),eventModal:document.getElementById('eventModal'),eventBadge:document.getElementById('eventBadge'),eventKind:document.getElementById('eventKind'),eventTitle:document.getElementById('eventTitle'),eventText:document.getElementById('eventText'),answerArea:document.getElementById('answerArea'),eventResult:document.getElementById('eventResult'),continueBtn:document.getElementById('continueBtn'),winnerModal:document.getElementById('winnerModal'),winnerTitle:document.getElementById('winnerTitle'),winnerText:document.getElementById('winnerText'),finalRanking:document.getElementById('finalRanking'),playAgainBtn:document.getElementById('playAgainBtn'),toast:document.getElementById('toast')});bind();renderPlayerInputs(2);
});
function bind(){
els.playerCount.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{const count=Number(btn.dataset.count);state.playerCount=count;els.playerCount.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn));renderPlayerInputs(count)}));
els.startBtn.addEventListener('click',startGame);
els.quickDemoBtn.addEventListener('click',()=>[...els.playerInputs.querySelectorAll('input')].forEach((input,i)=>input.value=DEMO_NAMES[i]||`Jogador ${i+1}`));
els.rollBtn.addEventListener('click',rollDice);els.newGameBtn.addEventListener('click',resetToSetup);els.playAgainBtn.addEventListener('click',resetToSetup);
els.soundBtn.addEventListener('click',()=>{state.sound=!state.sound;els.soundBtn.textContent=state.sound?'🔊':'🔇'});
els.fullscreenBtn.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()});
}
function renderPlayerInputs(count){const previous=[...els.playerInputs.querySelectorAll('input')].map(i=>i.value);els.playerInputs.innerHTML='';for(let i=0;i<count;i++){const row=document.createElement('label');row.className='player-input-row';row.innerHTML=`<span class="player-swatch" style="background:${COLORS[i]}">P${i+1}</span><input maxlength="18" placeholder="Nome do jogador ${i+1}" value="${escapeHtml(previous[i]||'')}" />`;els.playerInputs.appendChild(row)}}
function startGame(){const names=[...els.playerInputs.querySelectorAll('input')].map((input,i)=>input.value.trim()||`Jogador ${i+1}`);if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){showToast('Use nomes diferentes para os jogadores.');return}state.players=names.map((name,i)=>({id:i,name,color:COLORS[i],position:0,points:0,skip:0,finished:false}));state.current=0;state.round=1;state.awaiting=false;state.rolling=false;state.finishedOrder=[];buildBoard();els.gameLog.innerHTML='';log(`<b>Partida iniciada.</b> ${names.map(escapeHtml).join(', ')} estão no tabuleiro.`);els.setupScreen.classList.add('hidden');els.gameScreen.classList.remove('hidden');updateAll();beep(520,.08);setTimeout(()=>els.gameScreen.scrollIntoView({behavior:'smooth'}),60)}
function buildBoard(){[...els.gameBoard.querySelectorAll('.board-cell')].forEach(n=>n.remove());const coords=[];for(let c=0;c<10;c++)coords.push([1,c+1]);for(let r=1;r<7;r++)coords.push([r+1,10]);for(let c=8;c>=0;c--)coords.push([7,c+1]);for(let r=5;r>=1;r--)coords.push([r+1,1]);coords.forEach((rc,i)=>{const cell=document.createElement('div');const type=CELL_TYPES[i]||'normal';cell.className=`board-cell ${type}`;cell.dataset.pos=i;cell.style.gridRow=rc[0];cell.style.gridColumn=rc[1];const symbol=type==='quiz'?'?':type==='challenge'?'⚡':type==='bonus'?'★':type==='penalty'?'!':type==='event'?'◆':type==='finish'?'🏆':type==='start'?'▶':'';cell.innerHTML=`<span class="cell-number">${i}</span><span class="cell-symbol">${symbol}</span><span class="tokens"></span>`;els.gameBoard.appendChild(cell)})}
function rollDice(){if(state.rolling||state.awaiting)return;const p=currentPlayer();if(!p||p.finished){advanceTurn();return}if(p.skip>0){p.skip--;log(`<b>${escapeHtml(p.name)}</b> perde esta ronda devido a uma sanção.`);showToast(`${p.name} fica uma ronda sem jogar.`);beep(190,.14);advanceTurn();return}state.rolling=true;els.rollBtn.disabled=true;els.dice.classList.add('rolling');let ticks=0;const spin=setInterval(()=>{els.dice.textContent=FACES[Math.floor(Math.random()*6)];if(++ticks>=8){clearInterval(spin);const value=Math.floor(Math.random()*6)+1;els.dice.textContent=FACES[value-1];els.dice.classList.remove('rolling');beep(640,.07);movePlayer(p,value)}},70)}
function movePlayer(p,value){const from=p.position;p.position=Math.min(MAX_POS,p.position+value);log(`<b>${escapeHtml(p.name)}</b> lançou ${value} e avançou da casa ${from} para ${p.position}.`);animateTokenMove(p,from,p.position,()=>{state.rolling=false;if(p.position>=MAX_POS){finishPlayer(p);return}resolveCell(p)})}
function animateTokenMove(p,from,to,done){let step=from;const direction=to>=from?1:-1;const timer=setInterval(()=>{if(step===to){clearInterval(timer);renderTokens();done();return}step+=direction;const original=p.position;p.position=step;renderTokens();p.position=original;beep(350+step*4,.025)},90)}
function resolveCell(p){const type=CELL_TYPES[p.position]||'normal';if(type==='normal'||type==='start'){showToast(`${p.name}: casa neutra.`);advanceTurn();return}if(type==='quiz')return showQuiz(p);if(type==='challenge')return showChallenge(p);if(type==='bonus')return showAutoEvent(p,'BÓNUS','★',randomOf(BONUSES),'bonus');if(type==='penalty')return showAutoEvent(p,'SANÇÃO','!',randomOf(PENALTIES),'penalty');if(type==='event')return showAutoEvent(p,'EVENTO','◆',randomOf(EVENTS),'event')}
function showQuiz(p){state.awaiting=true;const q=randomOf(QUIZZES);openEvent('QUIZ','?',q.title,q.question);els.answerArea.className='answer-area';q.options.forEach((opt,i)=>{const btn=document.createElement('button');btn.className='answer-btn';btn.textContent=opt;btn.addEventListener('click',()=>{if(els.answerArea.dataset.locked==='1')return;els.answerArea.dataset.locked='1';[...els.answerArea.children].forEach((b,j)=>{if(j===q.answer)b.classList.add('correct');else if(j===i)b.classList.add('wrong');b.disabled=true});if(i===q.answer){p.points+=60;result(`Resposta correta. ${q.success}`,true);log(`<b>${escapeHtml(p.name)}</b> acertou o quiz e ganhou 60 pontos.`);beep(820,.12)}else{result(`Resposta incorreta. ${q.fail}`,false);log(`<b>${escapeHtml(p.name)}</b> não pontuou no quiz.`);beep(210,.16)}updateScores();els.continueBtn.classList.remove('hidden');els.continueBtn.onclick=()=>{closeEvent();advanceTurn()}});els.answerArea.appendChild(btn)})}
function showChallenge(p){state.awaiting=true;const c=randomOf(CHALLENGES);openEvent('DESAFIO','⚡',c.title,c.text);els.answerArea.className='answer-area one-column';const done=actionButton('Cumpri o desafio',()=>{p.points+=c.success;result(`Desafio cumprido: +${c.success} pontos.`,true);log(`<b>${escapeHtml(p.name)}</b> cumpriu o desafio e ganhou ${c.success} pontos.`);updateScores();lockAnswers();beep(780,.12);revealContinue()});const pass=actionButton('Passar o desafio',()=>{p.points=Math.max(0,p.points+c.skip);result(`Desafio passado: ${c.skip} pontos.`,false);log(`<b>${escapeHtml(p.name)}</b> passou o desafio (${c.skip} pontos).`);updateScores();lockAnswers();beep(220,.14);revealContinue()});els.answerArea.append(done,pass);els.continueBtn.onclick=()=>{closeEvent();advanceTurn()}}
function showAutoEvent(p,kind,badge,item,type){state.awaiting=true;openEvent(kind,badge,item.title,item.text);applyEffect(p,item,type);els.answerArea.className='answer-area one-column';els.answerArea.innerHTML='';result(effectSummary(item,type),type!=='penalty');revealContinue()}
function applyEffect(p,item,type){if(item.allPoints){state.players.forEach(pl=>pl.points+=item.allPoints);log(`<b>Evento coletivo:</b> todos ganharam ${item.allPoints} pontos.`)}else{if(item.points)p.points=Math.max(0,p.points+item.points);if(item.skip)p.skip+=item.skip;if(item.move){const old=p.position;p.position=Math.max(0,Math.min(MAX_POS,p.position+item.move));log(`<b>${escapeHtml(p.name)}</b> teve movimento adicional: ${old} → ${p.position}.`)}log(`<b>${escapeHtml(p.name)}</b> ativou: ${escapeHtml(item.title)}.`)}updateAll();beep(type==='penalty'?180:type==='bonus'?900:620,.12);if(p.position>=MAX_POS&&!p.finished)els.continueBtn.onclick=()=>{closeEvent();finishPlayer(p)};else els.continueBtn.onclick=()=>{closeEvent();advanceTurn()}}
function effectSummary(item,type){if(item.allPoints)return `Todos recebem +${item.allPoints} pontos.`;const parts=[];if(item.points)parts.push(`${item.points>0?'+':''}${item.points} pontos`);if(item.move)parts.push(`${item.move>0?'avança':'recua'} ${Math.abs(item.move)} ${Math.abs(item.move)===1?'casa':'casas'}`);if(item.skip)parts.push(`fica ${item.skip} ronda sem jogar`);return(type==='penalty'?'Consequência: ':'Efeito: ')+(parts.join(' · ')||'evento concluído')}
function finishPlayer(p){if(!p.finished){p.finished=true;p.points+=250;state.finishedOrder.push(p.id);log(`<b>${escapeHtml(p.name)}</b> chegou à meta e recebeu +250 pontos.`);showToast(`${p.name} chegou à meta!`);beep(1000,.22)}updateAll();setTimeout(showWinner,650)}
function advanceTurn(){state.awaiting=false;els.rollBtn.disabled=false;let attempts=0;do{state.current=(state.current+1)%state.players.length;if(state.current===0)state.round++;attempts++}while(state.players[state.current]?.finished&&attempts<=state.players.length);updateAll()}
function currentPlayer(){return state.players[state.current]}
function updateAll(){updateTurn();updateScores();renderTokens();els.playersAlive.textContent=`${state.players.filter(p=>!p.finished).length}/${state.players.length}`}
function updateTurn(){const p=currentPlayer();if(!p)return;els.turnName.textContent=p.name;els.turnToken.style.background=p.color;els.roundLabel.textContent=`Ronda ${state.round}`;els.centerMessage.textContent=p.finished?'Meta alcançada':`${p.name}, é a tua vez`;els.turnHint.textContent=p.skip>0?'Tens uma sanção pendente. Clica no dado para aplicar.':'Lança o dado e descobre a próxima casa.'}
function updateScores(){els.scoreList.innerHTML='';const ordered=[...state.players].sort((a,b)=>(b.position-a.position)||(b.points-a.points));ordered.forEach((p,index)=>{const row=document.createElement('div');row.className=`score-row ${p.id===state.current?'current':''} ${p.finished?'finished':''}`;row.innerHTML=`<span class="score-swatch" style="background:${p.color}">${initials(p.name)}</span><span class="score-info"><b>${escapeHtml(p.name)}</b><small>${p.finished?'Meta alcançada':`Casa ${p.position}`} · ${p.skip?`perde ${p.skip} ronda`:index===0?'na frente':'em jogo'}</small></span><span class="score-points"><b>${p.points}</b><small>pontos</small></span>`;els.scoreList.appendChild(row)})}
function renderTokens(){els.gameBoard.querySelectorAll('.tokens').forEach(t=>t.innerHTML='');state.players.forEach(p=>{const holder=els.gameBoard.querySelector(`[data-pos="${p.position}"] .tokens`);if(!holder)return;const token=document.createElement('span');token.className='token';token.style.background=p.color;token.textContent=p.id+1;token.title=p.name;holder.appendChild(token)})}
function openEvent(kind,badge,title,text){els.eventKind.textContent=kind;els.eventBadge.textContent=badge;els.eventTitle.textContent=title;els.eventText.textContent=text;els.eventResult.classList.add('hidden');els.eventResult.textContent='';els.answerArea.innerHTML='';delete els.answerArea.dataset.locked;els.continueBtn.classList.add('hidden');els.eventModal.classList.remove('hidden')}
function closeEvent(){els.eventModal.classList.add('hidden');state.awaiting=false}
function result(text,positive){els.eventResult.textContent=text;els.eventResult.style.background=positive?'#e4f7ed':'#ffe8eb';els.eventResult.style.color=positive?'#165c3d':'#8b1b2b';els.eventResult.classList.remove('hidden')}
function revealContinue(){els.continueBtn.classList.remove('hidden')}
function lockAnswers(){els.answerArea.querySelectorAll('button').forEach(b=>b.disabled=true)}
function actionButton(label,fn){const b=document.createElement('button');b.type='button';b.className='answer-btn';b.textContent=label;b.addEventListener('click',fn);return b}
function showWinner(){const ranking=[...state.players].sort((a,b)=>{if(a.finished!==b.finished)return a.finished?-1:1;return(b.position-a.position)||(b.points-a.points)});const winner=ranking[0];els.winnerTitle.textContent=`${winner.name} vence a demonstração!`;els.winnerText.textContent=`Chegou à meta com ${winner.points} pontos. Esta partida demonstrou o ciclo completo: turnos, dado, casas, quizzes, desafios, efeitos e classificação.`;els.finalRanking.innerHTML='';ranking.forEach((p,i)=>{const row=document.createElement('div');row.className='final-row';row.innerHTML=`<b>${i+1}º</b><span>${escapeHtml(p.name)} · casa ${p.position}</span><strong>${p.points} pts</strong>`;els.finalRanking.appendChild(row)});els.winnerModal.classList.remove('hidden')}
function resetToSetup(){els.winnerModal.classList.add('hidden');els.eventModal.classList.add('hidden');els.gameScreen.classList.add('hidden');els.setupScreen.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function log(html){const item=document.createElement('div');item.className='log-item';item.innerHTML=html;els.gameLog.prepend(item);while(els.gameLog.children.length>14)els.gameLog.lastChild.remove()}
function showToast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function randomOf(arr){return arr[Math.floor(Math.random()*arr.length)]}
function initials(name){return name.split(/\s+/).slice(0,2).map(p=>p[0]||'').join('').toUpperCase()}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function beep(freq=440,duration=.06){if(!state.sound)return;try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!beep.ctx)beep.ctx=new Ctx();const ctx=beep.ctx,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.stop(ctx.currentTime+duration)}catch(e){}}
