const FACES=['⚀','⚁','⚂','⚃','⚄','⚅'];
const COLORS=['#d80017','#2b7fff','#1da66b','#8e49e8'];
const DEMO_NAMES=['João Luís','Tomás','Ana','Carlos'];
const SVG_NS='http://www.w3.org/2000/svg';
const CHECKPOINTS=50;

const LEVELS=[
  {key:'M',name:'Origem',path:'M 60 185 L 60 35 L 245 145 L 430 35 L 430 185'},
  {key:'P',name:'História',path:'M 100 185 L 100 35 L 295 35 C 420 35 420 125 295 125 L 100 125'},
  {key:'L',name:'Organização',path:'M 125 35 L 125 180 L 430 180'},
  {key:'A',name:'Estatutos',path:'M 65 185 L 245 35 L 425 185 L 350 125 L 140 125 L 65 185'},
  {key:'★',name:'Conquista',path:'M 245 25 L 292 92 L 375 105 L 315 160 L 330 190 L 245 150 L 160 190 L 175 160 L 115 105 L 198 92 Z'}
];

const QUIZZES=[
{level:0,title:'Fundação do MPLA',question:'Qual é a data oficial da fundação do MPLA?',options:['10 de Dezembro de 1956','4 de Fevereiro de 1961','11 de Novembro de 1975','1 de Maio de 1958'],answer:0,source:'mpla.ao · História',note:'A fonte oficial identifica 10 de Dezembro de 1956 como data de fundação.'},
{level:0,title:'Primeira liderança',question:'Quem é apresentado na sequência histórica oficial como primeiro Presidente do MPLA?',options:['Agostinho Neto','Mário Pinto de Andrade','Ilídio Machado','José Eduardo dos Santos'],answer:2,source:'mpla.ao · Biografias',note:'Ilídio Machado surge como primeiro Presidente na sequência histórica oficial.'},
{level:0,title:'Identidade',question:'O que significa a sigla MPLA?',options:['Movimento Popular de Libertação de Angola','Movimento Patriótico Livre de Angola','Movimento Popular Laboral Angolano','Movimento para a Paz e Liberdade de Angola'],answer:0,source:'mpla.ao · O Partido',note:'MPLA significa Movimento Popular de Libertação de Angola.'},
{level:0,title:'Independência',question:'Quem proclamou a Independência Nacional de Angola em 11 de Novembro de 1975?',options:['Agostinho Neto','Ilídio Machado','Paulo Pombolo','Mário Pinto de Andrade'],answer:0,source:'mpla.ao · História',note:'António Agostinho Neto proclamou a Independência Nacional.'},
{level:0,title:'Data nacional',question:'Em que data se celebra a Independência Nacional de Angola?',options:['4 de Fevereiro','11 de Novembro','17 de Setembro','10 de Dezembro'],answer:1,source:'História de Angola',note:'11 de Novembro de 1975.'},
{level:0,title:'Memória do movimento',question:'Qual destas figuras presidiu o MPLA e foi o primeiro Presidente de Angola?',options:['Agostinho Neto','Paulo Pombolo','Mara Quiosa','Ilídio Machado'],answer:0,source:'mpla.ao · História',note:'Agostinho Neto.'},
{level:1,title:'Conferência Nacional',question:'Em que ano Agostinho Neto assumiu a presidência do MPLA na 1.ª Conferência Nacional?',options:['1956','1960','1962','1974'],answer:2,source:'mpla.ao · História',note:'A 1.ª Conferência Nacional ocorreu em 1962.'},
{level:1,title:'Hino do MPLA',question:'Segundo os Estatutos, como se chama o Hino do MPLA?',options:['Angola Avante','Com o povo heróico e generoso','Paz, Trabalho e Liberdade','Vitória é Certa'],answer:1,source:'Estatutos do MPLA · Artigo 7.º',note:'O hino é identificado como “Com o povo heróico e generoso”.'},
{level:1,title:'Emblema',question:'Que inscrição aparece no emblema do MPLA?',options:['Paz, Trabalho e Liberdade','Unidade, Disciplina e Vitória','Povo, Nação e Progresso','Trabalho, Justiça e Futuro'],answer:0,source:'Estatutos do MPLA · Artigo 6.º',note:'“Paz, Trabalho e Liberdade”.'},
{level:1,title:'Símbolo',question:'Quantas pontas tem a estrela descrita nos Estatutos do MPLA?',options:['4','5','6','8'],answer:1,source:'Estatutos do MPLA · Símbolos',note:'A estrela tem cinco pontas.'},
{level:1,title:'Cor amarela',question:'Segundo os Estatutos, o amarelo-vivo da bandeira representa:',options:['As riquezas do País','O continente africano','O sangue derramado','A organização de base'],answer:0,source:'Estatutos do MPLA · Símbolos',note:'O amarelo-vivo representa as riquezas do País.'},
{level:1,title:'Cor vermelha',question:'Na simbologia partidária, qual é uma das cores dominantes da bandeira do MPLA?',options:['Vermelho','Azul','Verde','Branco'],answer:0,source:'Estatutos do MPLA · Símbolos',note:'O vermelho integra a identidade visual do Partido.'},
{level:2,title:'Organização local',question:'Qual é a principal organização local do MPLA?',options:['Comité de Acção do MPLA (CAP)','Assembleia Nacional','Bureau Provincial','Comissão Eleitoral'],answer:0,source:'Regulamento das Organizações de Base · Artigo 10.º',note:'O CAP é a principal organização local.'},
{level:2,title:'Constituição de CAP',question:'Qual é o número mínimo de militantes indicado para criar um Comité de Acção do MPLA?',options:['5','10','15','25'],answer:2,source:'Regulamento das Organizações de Base · Artigo 10.º',note:'O regulamento estabelece um mínimo de 15 militantes.'},
{level:2,title:'Estrutura territorial',question:'Qual sequência corresponde à organização territorial indicada nos Estatutos?',options:['Base → comunal/distrito urbano → municipal → provincial → nacional','Bairro → comuna → país','Municipal → nacional → provincial','Provincial → base → municipal'],answer:0,source:'Estatutos do MPLA · Organização territorial',note:'A estrutura vai da base ao escalão nacional.'},
{level:2,title:'Órgão de base',question:'Qual sigla identifica o Comité de Acção do MPLA?',options:['CAP','CAM','CPM','CNM'],answer:0,source:'Regulamento das Organizações de Base',note:'CAP significa Comité de Acção do MPLA.'},
{level:2,title:'Escalão municipal',question:'Qual escalão se encontra entre o comunal/distrito urbano e o provincial?',options:['Municipal','Nacional','Bairro','Central'],answer:0,source:'Estatutos do MPLA · Organização territorial',note:'O escalão municipal antecede o provincial.'},
{level:2,title:'Liderança nacional',question:'Quem é o Secretário-Geral do MPLA?',options:['Paulo Pombolo','Mara Quiosa','Justino Capapinha','Luís Nunes'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'Paulo Pombolo é identificado como Secretário-Geral.'},
{level:3,title:'Natureza do Partido',question:'Segundo os Estatutos de 2025, o MPLA é definido como um partido:',options:['Nacional, independente, democrático, progressista e moderno','Regional e exclusivamente sindical','Confessional e local','Temporário e municipal'],answer:0,source:'Estatutos do MPLA · Artigo 8.º',note:'Formulação constante do Artigo 8.º.'},
{level:3,title:'Presidência atual',question:'Quem é o Presidente do MPLA?',options:['João Lourenço','Paulo Pombolo','Mara Quiosa','Roberto de Almeida'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'João Manuel Gonçalves Lourenço.'},
{level:3,title:'Vice-Presidência',question:'Quem é a Vice-Presidente do MPLA?',options:['Mara Quiosa','Emília Dias','Ângela Bragança','Nádia Monteiro'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'Mara Regina da Silva Baptista Domingos Quiosa.'},
{level:3,title:'Vida interna',question:'Qual documento estabelece princípios fundamentais de organização e funcionamento do Partido?',options:['Estatutos','Código Civil','Orçamento Geral do Estado','Lei Eleitoral'],answer:0,source:'Estatutos do MPLA',note:'Os Estatutos estabelecem as regras fundamentais do Partido.'},
{level:3,title:'Organização',question:'Qual destas opções corresponde a um escalão territorial partidário?',options:['Provincial','Judicial','Diplomático','Monetário'],answer:0,source:'Estatutos do MPLA',note:'O escalão provincial integra a organização territorial.'},
{level:3,title:'Base partidária',question:'As organizações de base aproximam a estrutura partidária de que realidade?',options:['Comunidades e militantes locais','Apenas instituições internacionais','Somente empresas privadas','Exclusivamente órgãos judiciais'],answer:0,source:'Regulamento das Organizações de Base',note:'As organizações de base atuam no nível local.'},
{level:4,title:'JMPLA',question:'Quem é o Primeiro Secretário Nacional da JMPLA?',options:['Justino Capapinha','Paulo Pombolo','Luís Nunes','Pereira Alfredo'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'Justino Capapinha.'},
{level:4,title:'OMA',question:'Quem é a Secretária-Geral da OMA?',options:['Emília Carlota Dias','Mara Quiosa','Nádia Monteiro','Maria Idalina Valente'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'Emília Carlota Dias.'},
{level:4,title:'Luanda',question:'Quem é identificado em 2026 como Primeiro Secretário Provincial do MPLA em Luanda?',options:['Luís Nunes','Pereira Alfredo','Eugénio Laborinho','Carla Cativa'],answer:0,source:'mpla.ao · Atualizado: ago. 2026',note:'Luís Manuel da Fonseca Nunes.'},
{level:4,title:'Órgãos nacionais',question:'Qual destes cargos integra a direção nacional do MPLA?',options:['Presidente do Partido','Governador do Banco Central','Provedor de Justiça','Presidente do Tribunal Supremo'],answer:0,source:'Estatutos do MPLA',note:'A Presidência do Partido integra a direção partidária.'},
{level:4,title:'Organização juvenil',question:'Qual é a organização juvenil ligada ao MPLA?',options:['JMPLA','OMA','CAP','CNE'],answer:0,source:'mpla.ao · Organizações sociais',note:'JMPLA é a organização juvenil.'},
{level:4,title:'Organização feminina',question:'Qual sigla identifica a Organização da Mulher Angolana ligada ao MPLA?',options:['OMA','JMPLA','CAP','FAA'],answer:0,source:'mpla.ao · Organizações sociais',note:'OMA significa Organização da Mulher Angolana.'}
];

const CHALLENGES=[
{title:'Memória Histórica',text:'Em 15 segundos, diga um acontecimento histórico ligado à independência de Angola.',success:70,skip:-10},
{title:'Estrutura de Base',text:'Explique em uma frase qual pode ser a utilidade de uma organização local bem coordenada.',success:65,skip:-10},
{title:'Símbolos',text:'Sem consultar o ecrã, diga uma das palavras da inscrição do emblema do MPLA.',success:60,skip:-10},
{title:'Organização',text:'Diga três escalões territoriais do Partido referidos nos Estatutos.',success:70,skip:-10},
{title:'Conhecimento Atual',text:'Diga o nome do Presidente, Vice-Presidente ou Secretário-Geral do MPLA.',success:65,skip:-10},
{title:'História rápida',text:'Diga o ano da Independência Nacional de Angola sem consultar o ecrã.',success:55,skip:-10}
];
const BONUSES=[
{title:'Conhecimento premiado',text:'Preparação reconhecida. Avance mais 3 checkpoints e ganhe 45 pontos.',move:3,points:45},
{title:'Espírito de equipa',text:'A equipa reconheceu o teu contributo. Ganhe 70 pontos.',move:0,points:70},
{title:'Participação ativa',text:'Avance 2 checkpoints e ganhe 50 pontos.',move:2,points:50}
];
const PENALTIES=[
{title:'Falta de preparação',text:'Recue 3 checkpoints e perca 20 pontos.',move:-3,points:-20},
{title:'Atraso na atividade',text:'Fique uma ronda sem jogar.',move:0,points:-10,skip:1},
{title:'Falha de coordenação',text:'Recue 2 checkpoints e perca 25 pontos.',move:-2,points:-25}
];
const EVENTS=[
{title:'Encontro de equipa',text:'Todos os jogadores recebem 20 pontos.',allPoints:20},
{title:'Ronda de conhecimento',text:'O jogador atual ganha 35 pontos.',points:35},
{title:'Ação comunitária',text:'Avance 3 checkpoints e ganhe 30 pontos.',move:3,points:30}
];

const state={players:[],current:0,round:1,awaiting:false,rolling:false,sound:true,playerCount:2,presentationPace:true,usedQuiz:new Set()};
const els={};let audioCtx=null;

document.addEventListener('DOMContentLoaded',()=>{
Object.assign(els,{setupScreen:id('setupScreen'),gameScreen:id('gameScreen'),playerCount:id('playerCount'),playerInputs:id('playerInputs'),presentationPace:id('presentationPace'),startBtn:id('startBtn'),quickDemoBtn:id('quickDemoBtn'),mplaMap:id('mplaMap'),boardScroll:id('boardScroll'),dice:id('dice'),rollBtn:id('rollBtn'),turnName:id('turnName'),turnToken:id('turnToken'),turnLevel:id('turnLevel'),roundLabel:id('roundLabel'),turnHint:id('turnHint'),centerMessage:id('centerMessage'),paceBadge:id('paceBadge'),scoreList:id('scoreList'),gameLog:id('gameLog'),playersAlive:id('playersAlive'),newGameBtn:id('newGameBtn'),soundBtn:id('soundBtn'),fullscreenBtn:id('fullscreenBtn'),eventModal:id('eventModal'),eventBadge:id('eventBadge'),eventKind:id('eventKind'),eventTitle:id('eventTitle'),eventText:id('eventText'),sourceNote:id('sourceNote'),answerArea:id('answerArea'),eventResult:id('eventResult'),continueBtn:id('continueBtn'),winnerModal:id('winnerModal'),winnerTitle:id('winnerTitle'),winnerText:id('winnerText'),finalRanking:id('finalRanking'),playAgainBtn:id('playAgainBtn'),toast:id('toast')});
bind();renderPlayerInputs(2);buildMap();
});
function id(x){return document.getElementById(x)}
function bind(){
els.playerCount.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{state.playerCount=Number(btn.dataset.count);els.playerCount.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn));renderPlayerInputs(state.playerCount)}));
els.startBtn.addEventListener('click',startGame);els.quickDemoBtn.addEventListener('click',()=>[...els.playerInputs.querySelectorAll('input')].forEach((input,i)=>input.value=DEMO_NAMES[i]||`Jogador ${i+1}`));els.rollBtn.addEventListener('click',rollDice);els.newGameBtn.addEventListener('click',resetToSetup);els.playAgainBtn.addEventListener('click',resetToSetup);els.soundBtn.addEventListener('click',()=>{state.sound=!state.sound;els.soundBtn.textContent=state.sound?'🔊':'🔇';if(state.sound)celebrateTone()});els.fullscreenBtn.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()});
}
function renderPlayerInputs(count){const prev=[...els.playerInputs.querySelectorAll('input')].map(i=>i.value);els.playerInputs.innerHTML='';for(let i=0;i<count;i++){const row=document.createElement('label');row.className='player-input-row';row.innerHTML=`<span class="player-swatch" style="background:${COLORS[i]}">P${i+1}</span><input maxlength="18" placeholder="Nome do jogador ${i+1}" value="${escapeHtml(prev[i]||'')}" />`;els.playerInputs.appendChild(row)}}
function startGame(){const names=[...els.playerInputs.querySelectorAll('input')].map((x,i)=>x.value.trim()||`Jogador ${i+1}`);if(new Set(names.map(n=>n.toLowerCase())).size!==names.length){toast('Use nomes diferentes.');return}state.presentationPace=!!els.presentationPace.checked;state.players=names.map((name,i)=>({id:i,name,color:COLORS[i],level:0,pos:0,points:0,skip:0,finished:false,levelsWon:0}));state.current=0;state.round=1;state.awaiting=false;state.rolling=false;state.usedQuiz=new Set();els.gameLog.innerHTML='';log(`<b>Partida iniciada.</b> ${names.map(escapeHtml).join(', ')} entram no nível M.`);els.setupScreen.classList.add('hidden');els.gameScreen.classList.remove('hidden');els.paceBadge.textContent=state.presentationPace?'⚡ Ritmo de apresentação ×3':'Ritmo normal ×1';updateAll();scrollToActiveLevel(true);beep(520,.12)}
function buildMap(){els.mplaMap.innerHTML='';LEVELS.forEach((level,li)=>{const card=document.createElement('section');card.className='level-card';card.dataset.level=li;card.innerHTML=`<div class="level-label"><strong>${level.key}</strong><small>NÍVEL ${li+1}</small><span>${level.name}</span></div><div class="level-progress-text">50 checkpoints</div>`;const svg=document.createElementNS(SVG_NS,'svg');svg.setAttribute('viewBox','0 0 500 220');svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.classList.add('level-svg');const glow=svgEl('path',{d:level.path,class:'route-glow'});const path=svgEl('path',{d:level.path,class:'route-line'});svg.append(glow,path);card.appendChild(svg);els.mplaMap.appendChild(card);requestAnimationFrame(()=>renderCheckpoints(svg,path,li))})}
function renderCheckpoints(svg,path,li){const len=path.getTotalLength();for(let i=0;i<CHECKPOINTS;i++){const pt=path.getPointAtLength(len*(i/(CHECKPOINTS-1)));const type=cellType(i,li);const g=svgEl('g',{class:`checkpoint ${type}`,'data-level':li,'data-pos':i});const special=type!=='normal';if(special)g.classList.add('special');const r=special?8:4.7;g.appendChild(svgEl('circle',{cx:pt.x,cy:pt.y,r:r+2,class:'node-ring'}));g.appendChild(svgEl('circle',{cx:pt.x,cy:pt.y,r,class:`node-dot ${type}`}));if(special){const t=svgEl('text',{x:pt.x,y:pt.y,class:'node-icon'});t.textContent=iconFor(type);g.appendChild(t)}else if(i%10===0){const t=svgEl('text',{x:pt.x,y:pt.y-10,class:'node-index'});t.textContent=i+1;g.appendChild(t)}svg.appendChild(g)}}
function cellType(i,li){if(i===0)return'start';if(i===CHECKPOINTS-1)return'finish';if(i%11===0)return'quiz';if(i%13===0)return'challenge';if(i%17===0)return'penalty';if(i%7===0)return'bonus';if((i+li)%19===0)return'event';return'normal'}
function iconFor(t){return{start:'▶',finish:'✓',quiz:'?',challenge:'⚡',bonus:'★',penalty:'!',event:'◆'}[t]||''}
function rollDice(){if(state.rolling||state.awaiting)return;const p=currentPlayer();if(!p||p.finished){advanceTurn();return}if(p.skip>0){p.skip--;log(`<b>${escapeHtml(p.name)}</b> perde esta ronda.`);toast(`${p.name} fica uma ronda sem jogar.`);beep(180,.18);advanceTurn();return}state.rolling=true;els.rollBtn.disabled=true;els.dice.classList.add('rolling');let ticks=0;const spin=setInterval(()=>{els.dice.textContent=FACES[Math.floor(Math.random()*6)];if(++ticks>=8){clearInterval(spin);const die=Math.floor(Math.random()*6)+1;els.dice.textContent=FACES[die-1];els.dice.classList.remove('rolling');const steps=die*(state.presentationPace?3:1);beep(680,.1);movePlayer(p,die,steps)}},65)}
function movePlayer(p,die,steps){const from=p.pos;const target=Math.min(CHECKPOINTS-1,p.pos+steps);log(`<b>${escapeHtml(p.name)}</b> lançou ${die}${state.presentationPace?` e avança ${steps} checkpoints`:''}.`);animateMove(p,from,target,()=>{state.rolling=false;if(p.pos>=CHECKPOINTS-1){completeLevel(p);return}resolveCell(p)})}
function animateMove(p,from,to,done){let step=from;const tick=()=>{if(step>=to){p.pos=to;renderTokens();done();return}step++;p.pos=step;renderTokens();beep(310+(step%20)*8,.025);setTimeout(tick,55)};tick()}
function completeLevel(p){p.points+=120;p.levelsWon++;levelFanfare();if(p.level>=LEVELS.length-1){p.finished=true;log(`<b>${escapeHtml(p.name)}</b> completou a estrela e venceu a Gincana!`);updateAll();setTimeout(showWinner,500);return}const won=LEVELS[p.level].key;p.level++;p.pos=0;log(`<b>${escapeHtml(p.name)}</b> conquistou o nível ${won} (+120) e desbloqueou ${LEVELS[p.level].key}.`);toast(`${p.name} conquistou ${won}! Próximo nível: ${LEVELS[p.level].key}`);updateAll();scrollToActiveLevel();setTimeout(advanceTurn,650)}
function resolveCell(p){const type=cellType(p.pos,p.level);if(type==='normal'||type==='start'){advanceTurn();return}if(type==='quiz')return showQuiz(p);if(type==='challenge')return showChallenge(p);if(type==='bonus')return showAuto(p,'BÓNUS','★',randomOf(BONUSES),'bonus');if(type==='penalty')return showAuto(p,'SANÇÃO','!',randomOf(PENALTIES),'penalty');if(type==='event')return showAuto(p,'EVENTO','◆',randomOf(EVENTS),'event')}
function showQuiz(p){state.awaiting=true;const pool=QUIZZES.filter(q=>q.level===p.level);let available=pool.filter(q=>!state.usedQuiz.has(`${p.level}:${q.title}`));if(!available.length){pool.forEach(q=>state.usedQuiz.delete(`${p.level}:${q.title}`));available=pool}const q=randomOf(available);state.usedQuiz.add(`${p.level}:${q.title}`);openEvent('QUIZ','?',q.title,q.question,q);q.options.forEach((opt,i)=>{const b=actionButton(opt,()=>{if(els.answerArea.dataset.locked==='1')return;els.answerArea.dataset.locked='1';[...els.answerArea.children].forEach((x,j)=>{x.disabled=true;if(j===q.answer)x.classList.add('correct');else if(j===i)x.classList.add('wrong')});if(i===q.answer){p.points+=60;result('Resposta correta · +60 pontos.',true);successTone();log(`<b>${escapeHtml(p.name)}</b> acertou: ${escapeHtml(q.title)}.`)}else{result(`Resposta incorreta. ${q.note}`,false);failTone();log(`<b>${escapeHtml(p.name)}</b> falhou o quiz.`)}updateScores();revealContinue(()=>{closeEvent();advanceTurn()})});els.answerArea.appendChild(b)})}
function showChallenge(p){state.awaiting=true;const c=randomOf(CHALLENGES);openEvent('DESAFIO','⚡',c.title,c.text);els.answerArea.className='answer-area one-column';els.answerArea.append(actionButton('Cumpri o desafio',()=>{p.points+=c.success;result(`Desafio cumprido · +${c.success} pontos.`,true);lockAnswers();successTone();updateScores();revealContinue(()=>{closeEvent();advanceTurn()})}),actionButton('Passar',()=>{p.points=Math.max(0,p.points+c.skip);result(`${c.skip} pontos.`,false);lockAnswers();failTone();updateScores();revealContinue(()=>{closeEvent();advanceTurn()})}))}
function showAuto(p,kind,badge,item,type){state.awaiting=true;openEvent(kind,badge,item.title,item.text);applyEffect(p,item);result(effectSummary(item),type!=='penalty');beep(type==='penalty'?170:type==='bonus'?900:620,.15);revealContinue(()=>{closeEvent();if(p.pos>=CHECKPOINTS-1)completeLevel(p);else advanceTurn()})}
function applyEffect(p,item){if(item.allPoints){state.players.forEach(x=>x.points+=item.allPoints)}else{if(item.points)p.points=Math.max(0,p.points+item.points);if(item.skip)p.skip+=item.skip;if(item.move)p.pos=Math.max(0,Math.min(CHECKPOINTS-1,p.pos+item.move))}updateAll()}
function effectSummary(item){const s=[];if(item.allPoints)s.push(`todos +${item.allPoints} pontos`);if(item.points)s.push(`${item.points>0?'+':''}${item.points} pontos`);if(item.move)s.push(`${item.move>0?'avança':'recua'} ${Math.abs(item.move)} checkpoints`);if(item.skip)s.push('perde 1 ronda');return s.join(' · ')||'Evento concluído.'}
function advanceTurn(){state.awaiting=false;els.rollBtn.disabled=false;let tries=0;do{state.current=(state.current+1)%state.players.length;if(state.current===0)state.round++;tries++}while(state.players[state.current]?.finished&&tries<=state.players.length);updateAll();scrollToActiveLevel()}
function currentPlayer(){return state.players[state.current]}
function updateAll(){updateTurn();updateScores();renderTokens();updateLevelCards();els.playersAlive.textContent=`${state.players.filter(p=>!p.finished).length}/${state.players.length}`}
function updateTurn(){const p=currentPlayer();if(!p)return;els.turnName.textContent=p.name;els.turnToken.style.background=p.color;els.turnLevel.textContent=`Nível ${LEVELS[p.level].key} · checkpoint ${p.pos+1}/50`;els.roundLabel.textContent=`Ronda ${state.round}`;els.centerMessage.textContent=`${LEVELS[p.level].key} · ${LEVELS[p.level].name}`;els.turnHint.textContent=p.skip?`Tem ${p.skip} ronda de penalização.`:'Lança o dado para avançar.'}
function updateScores(){const sorted=[...state.players].sort((a,b)=>b.level-a.level||b.pos-a.pos||b.points-a.points);els.scoreList.innerHTML='';sorted.forEach(p=>{const row=document.createElement('div');row.className='score-row'+(p.id===state.current?' current':'');row.innerHTML=`<span class="score-swatch" style="background:${p.color}">${initials(p.name)}</span><span class="score-info"><b>${escapeHtml(p.name)}</b><small>${p.finished?'Concluiu':`Nível ${LEVELS[p.level].key} · ${p.pos+1}/50`}</small></span><span class="score-points"><b>${p.points}</b><small>pts</small></span>`;els.scoreList.appendChild(row)})}
function renderTokens(){document.querySelectorAll('.player-token-group').forEach(n=>n.remove());state.players.forEach((p,i)=>{if(p.finished)return;const checkpoint=document.querySelector(`.checkpoint[data-level="${p.level}"][data-pos="${p.pos}"]`);if(!checkpoint)return;const dot=checkpoint.querySelector('.node-dot');const cx=Number(dot.getAttribute('cx'));const cy=Number(dot.getAttribute('cy'));const g=svgEl('g',{class:'player-token-group'});const offsets=[[-9,-10],[9,-10],[-9,10],[9,10]];const [ox,oy]=offsets[i]||[0,0];g.appendChild(svgEl('circle',{cx:cx+ox,cy:cy+oy,r:8,class:'player-token',fill:p.color}));const t=svgEl('text',{x:cx+ox,y:cy+oy,class:'player-token-label'});t.textContent=String(i+1);g.appendChild(t);checkpoint.parentNode.appendChild(g)})}
function updateLevelCards(){document.querySelectorAll('.level-card').forEach(card=>{const li=Number(card.dataset.level);card.classList.remove('active-level','completed-level');if(state.players.some(p=>!p.finished&&p.level===li))card.classList.add('active-level');if(state.players.length&&state.players.every(p=>p.finished||p.level>li))card.classList.add('completed-level')})}
function scrollToActiveLevel(immediate=false){if(!els.boardScroll||window.innerWidth<=820)return;const p=currentPlayer();if(!p)return;const card=document.querySelector(`.level-card[data-level="${p.level}"]`);if(!card)return;els.boardScroll.scrollTo({top:Math.max(0,card.offsetTop-8),behavior:immediate?'auto':'smooth'})}
function openEvent(kind,badge,title,text,q){els.eventKind.textContent=kind;els.eventBadge.textContent=badge;els.eventTitle.textContent=title;els.eventText.textContent=text;els.answerArea.innerHTML='';els.answerArea.className='answer-area';els.answerArea.dataset.locked='0';els.eventResult.classList.add('hidden');els.continueBtn.classList.add('hidden');if(q&&q.source){els.sourceNote.textContent=`Fonte: ${q.source}${q.note?` · ${q.note}`:''}`;els.sourceNote.classList.remove('hidden')}else els.sourceNote.classList.add('hidden');els.eventModal.classList.remove('hidden')}
function closeEvent(){els.eventModal.classList.add('hidden');state.awaiting=false}
function result(text,ok){els.eventResult.textContent=text;els.eventResult.style.color=ok?'#12613f':'#8c1424';els.eventResult.classList.remove('hidden')}
function revealContinue(fn){els.continueBtn.classList.remove('hidden');els.continueBtn.onclick=fn}
function lockAnswers(){els.answerArea.querySelectorAll('button').forEach(b=>b.disabled=true)}
function showWinner(){const ranked=[...state.players].sort((a,b)=>(b.finished-a.finished)||b.level-a.level||b.pos-a.pos||b.points-a.points);const winner=ranked[0];els.winnerTitle.textContent=`${winner.name} venceu!`;els.winnerText.textContent='Completou o circuito M → P → L → A → ★.';els.finalRanking.innerHTML='';ranked.forEach((p,i)=>{const r=document.createElement('div');r.className='final-row';r.innerHTML=`<b>${i+1}º</b><span>${escapeHtml(p.name)}</span><strong>${p.points} pts</strong>`;els.finalRanking.appendChild(r)});els.winnerModal.classList.remove('hidden');victoryTone()}
function resetToSetup(){els.winnerModal.classList.add('hidden');els.eventModal.classList.add('hidden');els.gameScreen.classList.add('hidden');els.setupScreen.classList.remove('hidden');state.players=[];state.current=0;state.round=1;state.awaiting=false;state.rolling=false;renderPlayerInputs(state.playerCount)}
function log(html){const d=document.createElement('div');d.className='log-item';d.innerHTML=html;els.gameLog.prepend(d);while(els.gameLog.children.length>35)els.gameLog.lastChild.remove()}
function toast(text){els.toast.textContent=text;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2300)}
function actionButton(text,fn){const b=document.createElement('button');b.type='button';b.className='answer-btn';b.textContent=text;b.addEventListener('click',fn);return b}
function randomOf(a){return a[Math.floor(Math.random()*a.length)]}
function initials(n){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function svgEl(name,attrs={}){const el=document.createElementNS(SVG_NS,name);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function beep(freq=440,dur=.08,gain=.22){if(!state.sound)return;try{const c=ensureAudio(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+dur)}catch(e){}}
function successTone(){beep(720,.09,.26);setTimeout(()=>beep(930,.13,.25),90)}function failTone(){beep(210,.18,.28)}function celebrateTone(){beep(620,.08,.26);setTimeout(()=>beep(820,.08,.26),90)}function levelFanfare(){[520,660,820,1040].forEach((f,i)=>setTimeout(()=>beep(f,.11,.28),i*90))}function victoryTone(){[520,660,780,980,1180].forEach((f,i)=>setTimeout(()=>beep(f,.18,.3),i*120))}